version: '3.7'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./laravel:/src:delegated
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated,ro
    environment:
      - VIRTUAL_HOST=cms.local.blw.sh
      - VIRTUAL_PORT=80
      - CERT_NAME=local.blw.sh
    expose:
      - 80
    working_dir: /src
  php:
    build:
      context: .
      dockerfile: ./etc/docker/php.producton.dockerfile
    volumes:
      - ./laravel:/src:delegated
      - /src/bootstrap
      - /src/vendor
      - /src/public
      - ./src:/package
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/00_mvc.ini:delegated,ro
    working_dir: /src
networks:
  default:
    external:
      name: proxy-network
