version: '3.7'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./laravel:/src:cached
      - ./src/public/index.php:/src/public/index.php:cached
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached,ro
    environment:
      - VIRTUAL_HOST=cms.local.blw.sh
      - VIRTUAL_PORT=80
      - CERT_NAME=local.blw.sh
    expose:
      - 80
    working_dir: /src
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./laravel:/src:cached
      - ./src:/package:cached
      - ./src/public/index.php:/src/public/index.php:cached
    working_dir: /src
networks:
  default:
    external:
      name: proxy-network
